config/routes.rb
Rails.application.routes.draw do
  resources :cards

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout',                  to: 'sessions#destroy', as: :logout

  root to: 'welcome#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  include CardEnum

  IMAGE_URL = 'http://wow.zamimg.com/images/hearthstone/cards/enus/medium'

  class << self
    def ransackable_attributes(auth_object = nil)
      %w(name card_type race rarity player_class set)
    end
  end

  def image
    "#{IMAGE_URL}/#{hearthstone_id}.png"
  end
end

app/models/concerns/card_enum.rb
module CardEnum
  extend ActiveSupport::Concern

  included do
    enum set: {
      Basic:                1,
      Classic:              2,
      Credits:              3,
      "Curse of Naxxramas": 4,
      Debug:                5,
      "Goblins vs Gnomes":  6,
      Missions:             7,
      Promotion:            8,
      Reward:               9,
      System:               10,
    }

    enum card_type: {
      Minion: 1,
      Spell:  2,
      Weapon: 3,
      Hero:   4,
    }

    enum player_class: {
      Neutral: 0, # undefined on AllSets.json
      Druid:   1,
      Hunter:  2,
      Mage:    3,
      Paladin: 4,
      Priest:  5,
      Rogue:   6,
      Shaman:  7,
      Warlock: 8,
      Warrior: 9,
    }

    enum rarity: {
      Free:      1,
      Common:    2,
      Rare:      3,
      Epic:      4,
      Legendary: 5,
    }

    enum race: {
      Beast:  1,
      Demon:  2,
      Dragon: 3,
      Mech:   4,
      Murloc: 5,
      Pirate: 6,
      Totem:  7,
    }

    enum faction: {
      Other:    1,  # Neutral on AllSets.json
      Alliance: 2,
      Horde:    3,
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  class << self
    def find_or_create_from_auth_hash(auth_hash)
      provider  = auth_hash[:provider]
      uid       = auth_hash[:uid]
      nickname  = auth_hash[:info][:nickname]
      image_url = auth_hash[:info][:image]

      User.find_or_create_by(provider: provider, uid: uid) do |user|
        user.nickname  = nickname
        user.image_url = image_url
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?

  private

  def logged_in?
    !!session[:user_id]
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @search       = Card.ransack(params[:q])
    @search.sorts = 'name asc'
    @cards        = @search.result.page(params[:page])
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:set, :hearthstone_id, :card_type, :name, :name_ja, :text, :text_ja, :collectible, :player_class, :cost, :attack, :health, :durability, :mechanics, :rarity, :faction, :race, :elite, :how_to_get, :how_to_get_gold, :in_play_text, :flavor, :artist)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = user.id
    redirect_to root_path, notice: 'ログインしました'
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/_cards.html.slim
= paginate @cards

- @cards.each do |card|
  .row
    .col-xs-6
      .panel.panel-primary
        p.panel-heading= card.name
        p.panel-body== card.text
        p.panel-body== card.text_ja
    .col-xs-6
      .thumbnail= image_tag card.image

= paginate @cards

app/views/cards/_form.html.slim
= form_for @card do |f|
  - if @card.errors.any?
    #error_explanation
      h2 = "#{pluralize(@card.errors.count, "error")} prohibited this card from being saved:"
      ul
        - @card.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :set
    = f.number_field :set
  .field
    = f.label :hearthstone_id
    = f.text_field :hearthstone_id
  .field
    = f.label :card_type
    = f.number_field :card_type
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :name_ja
    = f.text_field :name_ja
  .field
    = f.label :text
    = f.text_area :text
  .field
    = f.label :text_ja
    = f.text_area :text_ja
  .field
    = f.label :collectible
    = f.check_box :collectible
  .field
    = f.label :player_class
    = f.number_field :player_class
  .field
    = f.label :cost
    = f.number_field :cost
  .field
    = f.label :attack
    = f.number_field :attack
  .field
    = f.label :health
    = f.number_field :health
  .field
    = f.label :durability
    = f.number_field :durability
  .field
    = f.label :mechanics
    = f.text_area :mechanics
  .field
    = f.label :rarity
    = f.number_field :rarity
  .field
    = f.label :faction
    = f.number_field :faction
  .field
    = f.label :race
    = f.number_field :race
  .field
    = f.label :elite
    = f.check_box :elite
  .field
    = f.label :how_to_get
    = f.text_area :how_to_get
  .field
    = f.label :how_to_get_gold
    = f.text_area :how_to_get_gold
  .field
    = f.label :in_play_text
    = f.text_area :in_play_text
  .field
    = f.label :flavor
    = f.text_area :flavor
  .field
    = f.label :artist
    = f.text_field :artist
  .actions = f.submit

app/views/cards/edit.html.slim
h1 Editing card

== render 'form'

= link_to 'Show', @card
'|
= link_to 'Back', cards_path

app/views/cards/index.html.slim
= provide(:title, Card.model_name.human.pluralize)
= search_form_for @search, remote: true do |f|
  .form-group
    = f.label      :name_cont, 'カード名'
    = f.text_field :name_cont, class: 'form-control', placeholder: 'Card Name'
  .form-group
    = f.label      :card_type_in, 'カードタイプ'
    .clearfix
    - Card.card_types.each do |card_type, value|
      label.checkbox-inline
        = f.check_box(:card_type_in, {multiple: true}, value, nil)
        = card_type
    end
  .form-group
    = f.label      :race_in, '種族'
    .clearfix
    - Card.races.each do |race, value|
      label.checkbox-inline
        = f.check_box(:race_in, {multiple: true}, value, nil)
        = race
    end
  .form-group
    = f.label      :rarity_in, 'レアリティ'
    .clearfix
    - Card.rarities.each do |rarity, value|
      label.checkbox-inline
        = f.check_box(:rarity_in, {multiple: true}, value, nil)
        = rarity
    end
  .form-group
    = f.label      :player_class_in, 'クラス'
    .clearfix
    - Card.player_classes.each do |player_class, value|
      label.checkbox-inline
        = f.check_box(:player_class_in, {multiple: true}, value, nil)
        = player_class
    end
  .form-group
    = f.label      :set_in, 'カードセット'
    .clearfix
    - Card.sets.each do |set, value|
      label.checkbox-inline
        = f.check_box(:set_in, {multiple: true}, value, nil)
        = set
    end

#cards= render partial: 'cards'

app/views/cards/index.js.slim
| $('#cards').html("#{j(render 'cards')}");

app/views/cards/new.html.slim
h1 New card

== render 'form'

= link_to 'Back', cards_path

app/views/cards/show.html.slim
p#notice = notice

p
  strong Set:
  = @card.set
p
  strong Hearthstone:
  = @card.hearthstone_id
p
  strong Card type:
  = @card.card_type
p
  strong Name:
  = @card.name
p
  strong Name ja:
  = @card.name_ja
p
  strong Text:
  = @card.text
p
  strong Text ja:
  = @card.text_ja
p
  strong Collectible:
  = @card.collectible
p
  strong Player class:
  = @card.player_class
p
  strong Cost:
  = @card.cost
p
  strong Attack:
  = @card.attack
p
  strong Health:
  = @card.health
p
  strong Durability:
  = @card.durability
p
  strong Mechanics:
  = @card.mechanics
p
  strong Rarity:
  = @card.rarity
p
  strong Faction:
  = @card.faction
p
  strong Race:
  = @card.race
p
  strong Elite:
  = @card.elite
p
  strong How to get:
  = @card.how_to_get
p
  strong How to get gold:
  = @card.how_to_get_gold
p
  strong In play text:
  = @card.in_play_text
p
  strong Flavor:
  = @card.flavor
p
  strong Artist:
  = @card.artist

= link_to 'Edit', edit_card_path(@card)
'|
= link_to 'Back', cards_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title= yield :title
    meta name='viewport' content='width=device-width, initial-scale=1.0'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    header.navbar.navbar-default role='navigation'
      .container
        .navbar-header
          button.navbar-toggle data-target='#bs-example-navbar-collapse-1' type='button'
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'HscaliSearch', root_path, class: 'navbar-brand'
        .collapse.navbar-collapse id='bs-example-navbar-collapse-1'
          ul.nav.navbar-nav.navbar-right
            - if logged_in?
              li= link_to 'ログアウト', logout_path
            - else
              li= link_to 'Githubでログイン', '/auth/github'
    .container
      - if flash[:notice]
        .alert.alert-success
          = flash[:notice]
      = yield

app/views/welcome/index.html.slim
h1 Welcome#index
p Find me in app/views/welcome/index.html.slim